2022-02-06 20:27:03,336 INFO :: Debugging
2022-02-06 20:27:03,352 WARNING :: Warnings
2022-02-06 20:27:03,352 ERROR :: Errors
2022-02-06 20:33:50,396 INFO :: Debugging
2022-02-06 20:33:50,396 WARNING :: Warnings
2022-02-06 20:33:50,396 ERROR :: Errors
2022-02-07 01:09:11,079 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:09:53,407 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:16:33,906 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:16:41,510 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:19:23,662 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:20:54,533 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:22:32,077 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:22:38,044 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:22:55,604 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:23:48,484 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:23:58,780 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:24:01,232 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:24:03,763 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:24:06,263 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:24:28,742 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:25:00,573 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:26:17,647 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:27:22,079 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:27:48,149 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:30:11,718 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:30:31,689 INFO :: Binance Futures Client successfully Initialized
2022-02-07 01:30:58,875 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:17:46,787 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:17:47,354 ERROR :: Error while making GET request to /fapi/v1/account:{'code': -1021, 'msg': "Timestamp for this request was 1000ms ahead of the server's time."} (Error Code:400)
2022-02-09 22:18:25,888 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:18:26,405 ERROR :: Error while making GET request to /fapi/v1/account:{'code': -1021, 'msg': "Timestamp for this request was 1000ms ahead of the server's time."} (Error Code:400)
2022-02-09 22:18:44,791 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:18:45,398 ERROR :: Error while making GET request to /fapi/v1/account:{'code': -1021, 'msg': "Timestamp for this request was 1000ms ahead of the server's time."} (Error Code:400)
2022-02-09 22:25:37,271 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:40:07,416 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:41:52,104 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:42:37,362 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:43:11,590 INFO :: Binance Futures Client successfully Initialized
2022-02-09 22:44:24,551 INFO :: Binance Futures Client successfully Initialized
2022-03-01 18:19:20,538 INFO :: Binance connection opened
2022-03-01 18:19:40,559 ERROR :: Binance connection error: 
2022-03-01 18:19:40,669 ERROR :: error from callback <bound method BinanceFuturesClient.on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000024311D8B9D0>>: BinanceFuturesClient.on_close() takes 2 positional arguments but 4 were given
2022-03-01 18:19:40,669 ERROR :: Binance connection error: BinanceFuturesClient.on_close() takes 2 positional arguments but 4 were given
2022-03-01 18:19:40,673 INFO :: Binance Futures Client successfully Initialized
2022-03-01 18:28:03,252 INFO :: Binance Futures Client successfully Initialized
2022-03-01 18:28:03,925 INFO :: Binance connection opened
2022-03-02 10:32:20,178 INFO :: Binance Futures Client successfully Initialized
2022-03-02 10:32:21,533 INFO :: Binance connection opened
2022-03-02 10:38:01,159 INFO :: Binance Futures Client successfully Initialized
2022-03-02 10:38:02,139 INFO :: Binance connection opened
2022-03-02 10:39:34,222 INFO :: Binance Futures Client successfully Initialized
2022-03-02 10:39:34,884 INFO :: Binance connection opened
2022-03-19 10:35:07,452 INFO :: Binance Futures Client successfully Initialized
2022-03-19 10:35:08,735 INFO :: Binance connection opened
2022-03-19 10:35:08,735 ERROR :: error from callback <bound method BinanceFuturesClient.on_open of <connectors.binance_futures.BinanceFuturesClient object at 0x000002BC12D40040>>: 'str' object has no attribute 'symbol'
2022-03-19 10:35:08,735 ERROR :: Binance connection error: 'str' object has no attribute 'symbol'
2022-03-19 11:24:08,935 ERROR :: Binance connection error: Connection to remote host was lost.
2022-03-19 11:24:08,936 ERROR :: error from callback <bound method BinanceFuturesClient.on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002BC12D40040>>: BinanceFuturesClient.on_close() takes 2 positional arguments but 4 were given
2022-03-19 11:24:08,936 ERROR :: Binance connection error: BinanceFuturesClient.on_close() takes 2 positional arguments but 4 were given
2022-03-19 11:24:52,579 INFO :: Binance Futures Client successfully Initialized
2022-03-19 11:24:53,516 INFO :: Binance connection opened
2022-03-19 11:24:53,516 ERROR :: error from callback <bound method BinanceFuturesClient.on_open of <connectors.binance_futures.BinanceFuturesClient object at 0x0000020D64276080>>: 'str' object has no attribute 'symbol'
2022-03-19 11:24:53,516 ERROR :: Binance connection error: 'str' object has no attribute 'symbol'
2022-03-29 21:13:21,489 INFO :: Binance Futures Client successfully Initialized
2022-03-29 21:13:22,863 INFO :: Binance connection opened
2022-03-29 21:13:22,863 ERROR :: error from callback <bound method BinanceFuturesClient.on_open of <connectors.binance_futures.BinanceFuturesClient object at 0x00000158167165F0>>: 'str' object has no attribute 'symbol'
2022-03-29 21:13:22,863 ERROR :: Binance connection error: 'str' object has no attribute 'symbol'
2022-03-29 21:22:10,965 INFO :: Binance Futures Client successfully Initialized
2022-03-29 21:22:11,636 INFO :: Binance connection opened
2022-03-29 21:22:11,636 ERROR :: error from callback <bound method BinanceFuturesClient.on_open of <connectors.binance_futures.BinanceFuturesClient object at 0x000001E977DF6410>>: 'str' object has no attribute 'symbol'
2022-03-29 21:22:11,636 ERROR :: Binance connection error: 'str' object has no attribute 'symbol'
2022-03-30 22:11:39,682 INFO :: Binance Futures Client successfully Initialized
2022-03-30 22:11:41,164 INFO :: Binance connection opened
2022-04-03 11:41:37,105 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:37,106 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:41:39,118 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:41,124 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:43,137 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:45,153 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:47,160 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:49,168 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:51,194 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:53,209 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:55,214 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:57,227 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:41:59,238 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:01,249 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:03,260 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:05,274 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:07,290 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:09,295 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:11,301 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:13,302 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:15,313 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:17,319 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:19,323 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:21,336 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:23,347 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:25,362 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:27,371 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:29,381 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:31,383 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:33,389 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:35,401 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:37,417 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:39,424 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:41,430 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:43,437 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:45,441 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:47,452 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:49,461 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:51,471 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:53,481 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:55,487 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:57,492 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:42:59,501 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:01,504 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:03,520 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:05,522 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:07,530 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:09,545 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:11,561 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:13,566 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:15,576 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:17,592 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:19,596 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:21,601 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:23,610 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:25,612 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:27,615 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:29,618 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:34,813 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:34,813 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:43:36,835 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:38,846 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:40,854 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:42,864 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:44,872 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:46,880 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:48,887 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:50,901 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:52,913 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:54,919 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:56,924 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:43:58,934 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:00,940 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:02,953 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:04,961 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:06,965 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:14,299 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:16,314 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:18,319 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:20,332 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:22,335 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:24,337 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:26,348 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:28,369 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:30,383 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:32,394 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:34,397 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:36,403 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:38,418 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:40,432 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:45,873 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:45,873 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:44:47,876 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:49,878 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:51,891 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:53,897 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:55,908 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:57,914 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:44:59,922 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:01,936 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:31,531 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:31,532 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:45:32,552 INFO :: Bitmex Client Successfully Initialized
2022-04-03 11:45:33,817 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:35,845 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:37,854 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:39,866 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:41,867 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:43,869 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:45,873 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:47,876 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:49,886 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:51,890 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:53,905 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:55,911 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:57,924 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:45:59,928 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:01,937 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:03,943 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:05,948 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:07,959 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:09,972 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:11,985 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:14,001 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:16,006 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:18,009 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:20,019 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:22,031 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:24,035 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:26,048 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:28,078 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:30,093 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:32,095 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:34,098 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:36,110 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:38,116 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:40,126 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:42,129 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:44,140 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:46,150 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:48,161 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:50,166 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:52,171 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:54,182 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:56,190 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:46:58,206 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:00,209 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:02,441 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:04,449 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:06,451 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:08,459 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:10,471 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:12,480 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:14,482 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:16,487 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:18,489 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:20,494 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:22,496 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:24,501 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:26,505 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:28,510 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:30,523 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:32,537 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:34,543 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:36,553 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:38,556 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:40,560 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:42,573 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:44,589 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:46,592 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:48,606 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:52,235 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:52,235 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:47:54,239 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:56,251 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:47:58,253 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:00,260 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:02,264 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:04,274 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:06,284 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:08,295 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:11,164 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:11,164 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:48:13,170 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:15,187 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:48:17,190 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:07,797 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:07,800 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:51:09,811 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:10,104 INFO :: Bitmex Client Successfully Initialized
2022-04-03 11:51:11,816 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:13,824 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:15,828 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:17,840 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:19,842 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:21,849 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:51:23,855 ERROR :: Binance error in run_forever() method: 'NoneType' object has no attribute 'run_forever'
2022-04-03 11:56:43,074 INFO :: Binance Futures Client successfully Initialized
2022-04-03 11:56:43,939 INFO :: Binance connection opened
2022-04-03 11:56:44,420 INFO :: Bitmex Client Successfully Initialized
2022-04-03 12:58:01,200 INFO :: Binance Futures Client successfully Initialized
2022-04-03 12:58:02,465 INFO :: Binance connection opened
2022-04-03 12:58:02,636 INFO :: Bitmex Client Successfully Initialized
2022-04-03 12:58:03,156 ERROR :: Error while making POST request to /api/v1/order:{'error': {'message': 'Invalid leavesQty for lotSize', 'name': 'HTTPError'}} (Error Code:400)
2022-04-03 12:58:38,540 INFO :: Binance Futures Client successfully Initialized
2022-04-03 12:58:39,345 INFO :: Binance connection opened
2022-04-03 12:58:39,526 INFO :: Bitmex Client Successfully Initialized
2022-04-03 12:58:39,941 ERROR :: Error while making POST request to /api/v1/order:{'error': {'message': 'Invalid leavesQty for lotSize', 'name': 'HTTPError'}} (Error Code:400)
2022-04-03 12:59:56,296 INFO :: Binance Futures Client successfully Initialized
2022-04-03 12:59:57,734 INFO :: Binance connection opened
2022-04-03 12:59:58,277 INFO :: Bitmex Client Successfully Initialized
2022-04-03 13:01:08,601 INFO :: Binance Futures Client successfully Initialized
2022-04-03 13:01:09,995 INFO :: Binance connection opened
2022-04-03 13:01:10,347 INFO :: Bitmex Client Successfully Initialized
2022-04-03 13:03:34,915 INFO :: Binance Futures Client successfully Initialized
2022-04-03 13:03:36,208 INFO :: Binance connection opened
2022-04-03 13:03:36,698 INFO :: Bitmex Client Successfully Initialized
2022-04-03 13:05:34,639 INFO :: Binance Futures Client successfully Initialized
2022-04-03 13:05:36,033 INFO :: Binance connection opened
2022-04-03 13:05:36,239 INFO :: Bitmex Client Successfully Initialized
2022-04-03 13:05:51,689 INFO :: Binance Futures Client successfully Initialized
2022-04-03 13:05:52,855 INFO :: Binance connection opened
2022-04-03 13:05:53,489 INFO :: Bitmex Client Successfully Initialized
2022-04-03 13:06:14,283 INFO :: Binance Futures Client successfully Initialized
2022-04-03 13:06:15,367 INFO :: Binance connection opened
2022-04-03 13:06:15,528 INFO :: Bitmex Client Successfully Initialized
2022-04-03 13:06:30,705 INFO :: Binance Futures Client successfully Initialized
2022-04-03 13:06:31,580 INFO :: Binance connection opened
2022-04-03 13:06:32,941 INFO :: Bitmex Client Successfully Initialized
2022-04-04 10:43:07,748 INFO :: Binance Futures Client successfully Initialized
2022-04-04 10:43:08,723 INFO :: Binance connection opened
2022-04-04 10:43:09,153 INFO :: Bitmex Client Successfully Initialized
2022-04-04 10:44:14,074 INFO :: Binance Futures Client successfully Initialized
2022-04-04 10:44:14,878 INFO :: Binance connection opened
2022-04-04 10:44:15,093 INFO :: Bitmex Client Successfully Initialized
2022-04-04 10:44:16,326 INFO :: Bitmex connection opened
2022-04-04 10:44:20,209 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,209 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,210 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,210 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,210 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,210 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,210 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,210 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,210 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,210 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,211 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,211 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,211 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,211 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,211 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,211 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,211 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,211 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,211 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,211 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,211 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,211 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,213 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,213 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,213 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,213 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,213 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,213 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,213 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,213 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,213 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,213 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,214 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,214 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,214 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,214 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,215 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,215 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,215 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,215 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,215 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,215 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,215 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,215 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,216 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,216 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,216 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,216 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,216 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,216 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,216 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,216 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,217 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,217 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,217 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,217 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,217 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,217 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,217 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,217 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,217 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,217 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,217 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,229 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,230 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,230 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,231 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,231 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,232 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,232 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,234 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,234 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,234 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,234 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,243 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,243 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,243 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,244 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,244 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,244 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,244 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,244 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,244 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,245 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,245 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,245 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,245 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,245 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,245 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,245 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,246 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,246 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,246 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,246 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,246 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,651 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,651 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,651 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,651 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,651 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,651 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,651 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,651 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,655 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,655 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,655 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,655 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,655 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,655 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,655 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,655 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,656 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,656 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,656 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,656 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,656 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,656 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,657 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,657 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,657 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,657 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,657 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,657 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,657 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,658 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,658 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,658 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,658 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,658 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,658 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,658 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,659 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,659 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,659 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,659 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,659 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,659 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,660 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,660 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,660 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,660 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,660 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,660 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,661 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,661 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,661 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,661 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,661 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,661 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,661 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,670 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,670 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,670 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,670 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,670 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,671 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,671 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,671 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,671 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,671 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,671 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,671 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,671 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,672 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,672 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,672 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,672 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,672 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,672 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,672 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,675 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,675 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,675 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,685 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,685 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,685 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,687 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,687 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,699 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,699 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,699 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,700 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,700 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,700 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,702 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,702 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,702 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,702 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,702 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,702 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,702 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,702 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,703 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,703 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,703 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,704 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,713 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,713 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,714 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,714 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,714 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,714 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,714 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,714 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,714 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,716 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,716 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,716 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,716 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,716 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,716 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,716 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,716 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,716 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,716 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,716 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,717 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,717 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,717 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,718 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,730 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,730 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,730 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,730 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,730 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,858 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,859 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,860 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,860 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,862 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,862 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,863 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,863 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,863 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,863 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,867 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,868 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,869 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,869 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,871 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,871 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,872 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,872 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,873 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,873 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,874 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,875 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,875 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,876 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,877 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,877 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,878 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,878 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,879 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,879 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,880 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,881 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,881 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,881 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,882 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,882 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,882 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,883 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,883 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,884 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,884 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,884 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,885 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,885 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,885 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,885 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,887 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,887 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,888 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,888 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,888 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,889 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,889 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,889 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,890 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,890 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,891 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,891 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,892 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,892 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,892 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,893 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,893 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,893 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,893 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,893 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,894 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,894 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,894 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,894 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,894 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,894 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,895 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,895 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,895 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,895 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,895 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,895 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,896 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,896 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,896 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,896 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,897 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,897 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,897 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,897 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,897 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,898 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,898 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,898 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,898 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,898 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,898 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,904 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:20,904 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:20,904 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:22,590 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:22,591 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:23,693 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:23,694 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:23,849 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:23,850 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,557 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,557 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,565 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,566 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,566 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,566 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,566 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,566 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,566 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,566 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,570 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,570 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,571 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,571 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,571 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,571 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,571 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,574 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,575 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,576 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,576 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,576 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,576 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,576 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:24,576 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:24,576 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,649 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,649 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,650 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,650 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,650 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,650 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,651 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,651 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,651 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,652 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,652 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,654 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,654 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,655 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,655 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,656 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,656 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,656 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,657 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,657 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,657 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,658 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,658 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,659 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,659 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,659 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,660 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,660 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,660 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,661 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,661 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,661 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,661 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,662 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,662 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,662 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,663 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,663 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,663 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,664 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,664 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,665 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,665 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,666 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,667 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,667 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,667 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,668 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,670 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,670 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,671 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,672 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,672 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,672 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,673 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,673 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,674 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,674 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,674 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,674 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,675 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,675 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,676 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,676 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,677 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,677 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,677 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,677 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,677 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,677 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,677 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,677 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,677 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,677 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,680 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,680 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,680 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,680 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,682 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,682 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,682 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,682 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,683 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,683 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,683 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,684 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,685 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,685 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,686 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,686 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,690 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,690 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,690 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,690 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,691 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,691 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,691 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,691 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,691 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,691 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,692 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,692 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,692 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,699 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,699 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,699 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,699 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,699 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,700 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,700 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,700 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,700 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,701 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,701 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,702 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,702 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,702 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,703 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,703 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,703 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,703 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,704 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,704 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,704 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,704 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,704 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,714 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,715 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,715 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,717 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,717 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,717 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,717 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,718 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,718 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,718 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,718 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,719 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,719 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,719 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,719 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,719 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,719 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,719 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,720 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,720 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,720 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,720 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,720 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,720 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,720 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,721 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,721 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,721 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,728 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,728 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,728 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,729 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,729 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,729 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,729 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,729 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,729 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,730 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,730 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,730 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,730 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,730 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,730 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,731 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,731 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,732 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,732 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,732 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,732 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,732 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:44:25,732 ERROR :: error from callback <bound method BitmexClient._on_message of <connectors.bitmex.BitmexClient object at 0x0000018E8E8AE7A0>>: 'symbol'
2022-04-04 10:44:25,732 ERROR :: Bitmex connection error: 'symbol'
2022-04-04 10:45:45,305 INFO :: Binance Futures Client successfully Initialized
2022-04-04 10:45:46,019 INFO :: Binance connection opened
2022-04-04 10:45:46,231 INFO :: Bitmex Client Successfully Initialized
2022-04-04 10:45:47,072 INFO :: Bitmex connection opened
2022-04-04 12:42:31,750 INFO :: Binance Futures Client successfully Initialized
2022-04-04 12:42:32,324 INFO :: Binance connection opened
2022-04-04 12:42:32,527 INFO :: Bitmex Client Successfully Initialized
2022-04-04 12:42:33,240 INFO :: Bitmex connection opened
2022-04-04 12:44:40,251 INFO :: Binance Futures Client successfully Initialized
2022-04-04 12:44:40,853 INFO :: Binance connection opened
2022-04-04 12:44:41,110 INFO :: Bitmex Client Successfully Initialized
2022-04-04 12:44:42,130 INFO :: Bitmex connection opened
2022-04-05 09:35:54,104 INFO :: Binance Futures Client successfully Initialized
2022-04-05 09:35:55,098 INFO :: Binance connection opened
2022-04-05 09:36:00,032 INFO :: Bitmex Client Successfully Initialized
2022-04-05 09:36:02,863 INFO :: Bitmex connection opened
2022-04-05 09:41:59,507 ERROR :: Error while making GET request to /fapi/v1/account:{'code': -1021, 'msg': 'Timestamp for this request is outside of the recvWindow.'} (Error Code:400)
2022-04-05 09:41:59,519 INFO :: Binance Futures Client successfully Initialized
2022-04-05 09:42:10,910 INFO :: Binance connection opened
2022-04-05 09:42:11,296 ERROR :: Error while making GET request to /api/v1/user/margin:{'error': {'message': 'This request has expired - `expires` is in the past. Current time: 1649131931', 'name': 'HTTPError'}} (Error Code:400)
2022-04-05 09:42:11,297 INFO :: Bitmex Client Successfully Initialized
2022-04-05 09:42:16,722 INFO :: Bitmex connection opened
2022-04-05 09:44:50,528 ERROR :: Connection Error while making GET request to /fapi/v1/account: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-04-05 09:44:50,529 INFO :: Binance Futures Client successfully Initialized
2022-04-05 09:45:02,280 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:02,281 ERROR :: Connection Error while making GET request to /api/v1/instrument/active: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/instrument/active (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D141E5E10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-05 09:45:02,282 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000021D142121A0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:02,284 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:14,336 ERROR :: Connection Error while making GET request to /api/v1/user/margin: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/user/margin?currency=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D141E5E70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-05 09:45:14,338 INFO :: Bitmex Client Successfully Initialized
2022-04-05 09:45:16,344 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:16,344 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000021D142121A0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:16,344 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:26,369 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:26,370 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000021D141E5600>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:26,370 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:28,405 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:28,405 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000021D141E5600>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:28,405 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:30,402 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:30,403 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000021D142121A0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:30,403 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:30,418 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:30,418 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000021D141E5600>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:30,419 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:46,120 ERROR :: Connection Error while making GET request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F65AA05FC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-05 09:45:58,175 ERROR :: Connection Error while making GET request to /fapi/v1/account: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/account?timestamp=1649132146120&signature=56fd70972d88e47d7602c8af14454e7b9109250158ecf8cb6aad9a227c2ce491 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F65AA06350>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-05 09:45:58,177 INFO :: Binance Futures Client successfully Initialized
2022-04-05 09:45:58,177 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:58,177 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:58,182 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:58,187 ERROR :: Connection Error while making GET request to /api/v1/instrument/active: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/instrument/active (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F65AA06020>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-05 09:45:58,190 ERROR :: Connection Error while making GET request to /api/v1/user/margin: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/user/margin?currency=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F65AA064D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-05 09:45:58,195 INFO :: Bitmex Client Successfully Initialized
2022-04-05 09:45:58,196 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:45:58,196 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:45:58,196 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:00,188 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:00,188 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:00,188 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:00,200 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:00,201 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:00,201 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:02,198 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:02,198 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:02,199 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:02,212 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:02,212 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:02,212 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:04,214 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:04,218 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:04,219 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:04,219 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:04,219 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:04,220 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:06,226 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:06,226 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:06,227 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:06,227 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:06,227 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:06,227 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:16,258 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:16,258 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:16,258 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:20,282 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-05 09:46:20,282 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:20,282 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:20,395 ERROR :: Binance connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
2022-04-05 09:46:20,396 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:20,396 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:22,455 ERROR :: Bitmex connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
2022-04-05 09:46:22,455 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:22,456 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:22,467 ERROR :: Binance connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
2022-04-05 09:46:22,468 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001F65AA04E50>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:22,468 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:24,519 ERROR :: Bitmex connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
2022-04-05 09:46:24,519 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001F65AA053C0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:24,519 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 09:46:25,065 INFO :: Binance connection opened
2022-04-05 09:46:27,173 INFO :: Bitmex connection opened
2022-04-05 09:46:44,607 INFO :: Binance Futures Client successfully Initialized
2022-04-05 09:46:45,133 INFO :: Binance connection opened
2022-04-05 09:46:45,657 INFO :: Bitmex Client Successfully Initialized
2022-04-05 09:46:46,336 INFO :: Bitmex connection opened
2022-04-05 09:48:22,853 INFO :: Binance Futures Client successfully Initialized
2022-04-05 09:48:23,491 INFO :: Binance connection opened
2022-04-05 09:48:24,458 INFO :: Bitmex Client Successfully Initialized
2022-04-05 09:48:25,089 INFO :: Bitmex connection opened
2022-04-05 10:02:44,258 INFO :: Binance Futures Client successfully Initialized
2022-04-05 10:02:46,896 INFO :: Binance connection opened
2022-04-05 10:02:49,438 ERROR :: Error while making GET request to /api/v1/instrument/active:{'error': {'message': 'This request has expired - `expires` is in the past. Current time: 1649133169', 'name': 'HTTPError'}} (Error Code:400)
2022-04-05 10:03:09,400 ERROR :: Connection Error while making GET request to /api/v1/user/margin: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/user/margin?currency=all (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
2022-04-05 10:03:09,402 INFO :: Bitmex Client Successfully Initialized
2022-04-05 10:03:30,458 ERROR :: Bitmex connection error: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
2022-04-05 10:03:30,460 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000025512CF5390>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 10:03:30,460 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-05 10:04:33,990 INFO :: Binance Futures Client successfully Initialized
2022-04-05 10:04:34,624 INFO :: Binance connection opened
2022-04-05 10:04:36,570 INFO :: Bitmex Client Successfully Initialized
2022-04-05 10:04:37,296 INFO :: Bitmex connection opened
2022-04-05 10:04:37,548 ERROR :: Error while making POST request to /api/v1/order:{'error': {'message': 'Invalid orderQty', 'name': 'ValidationError'}} (Error Code:400)
2022-04-05 10:04:58,766 INFO :: Binance Futures Client successfully Initialized
2022-04-05 10:05:00,587 INFO :: Bitmex Client Successfully Initialized
2022-04-05 10:05:01,023 INFO :: Binance connection opened
2022-04-05 10:05:01,275 INFO :: Bitmex connection opened
2022-04-05 10:27:05,840 INFO :: Binance Futures Client successfully Initialized
2022-04-05 10:27:06,438 INFO :: Binance connection opened
2022-04-05 10:27:07,023 INFO :: Bitmex Client Successfully Initialized
2022-04-05 10:27:07,743 INFO :: Bitmex connection opened
2022-04-05 10:28:31,771 INFO :: Binance Futures Client successfully Initialized
2022-04-05 10:28:32,354 INFO :: Binance connection opened
2022-04-05 10:28:33,358 INFO :: Bitmex Client Successfully Initialized
2022-04-05 10:28:34,205 INFO :: Bitmex connection opened
2022-04-05 10:33:42,996 INFO :: Binance Futures Client successfully Initialized
2022-04-05 10:33:43,626 INFO :: Binance connection opened
2022-04-05 10:33:44,107 INFO :: Bitmex Client Successfully Initialized
2022-04-05 10:33:44,923 INFO :: Bitmex connection opened
2022-04-12 08:58:31,536 INFO :: Binance Futures Client successfully Initialized
2022-04-12 08:58:32,092 INFO :: Binance connection opened
2022-04-12 08:58:32,398 INFO :: Bitmex Client Successfully Initialized
2022-04-12 08:58:34,193 INFO :: Bitmex connection opened
2022-04-12 09:11:12,651 ERROR :: Connection Error while making GET request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023379C9ABF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:11:12,658 ERROR :: Connection Error while making GET request to /fapi/v1/account: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/account?timestamp=1649734872652&signature=6f74fd5e08f1fed05b7bd1aa9c694629436eb4ef6efb8ce643af4b4c1d64d07c (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023379C9B790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:11:12,661 INFO :: Binance Futures Client successfully Initialized
2022-04-12 09:11:12,662 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:12,663 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000023379C9A3B0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:12,663 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:12,672 ERROR :: Connection Error while making GET request to /api/v1/instrument/active: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/instrument/active (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023379C9BB50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:11:12,677 ERROR :: Connection Error while making GET request to /api/v1/user/margin: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/user/margin?currency=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023379C9B910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:11:12,680 INFO :: Bitmex Client Successfully Initialized
2022-04-12 09:11:13,251 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:13,251 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000023379C9B580>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:13,251 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:14,671 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:14,671 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000023379C9A3B0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:14,671 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:15,256 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:15,256 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000023379C9B580>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:15,257 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:16,678 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:16,678 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000023379C9A3B0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:16,679 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:17,263 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:17,264 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x0000023379C9B580>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:17,264 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:18,685 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:18,685 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000023379C9A3B0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:18,686 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:20,697 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:20,698 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000023379C9A3B0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:20,698 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:22,707 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:11:22,709 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x0000023379C9A3B0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:11:22,709 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:12,642 ERROR :: Connection Error while making GET request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ABB1F5A4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:12:24,703 ERROR :: Connection Error while making GET request to /fapi/v1/account: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/account?timestamp=1649734932643&signature=55b157a9fa003e50d4f712220ca2468988c63917943829c07b8877789a6601b7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ABB1F5A860>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:12:24,707 INFO :: Binance Futures Client successfully Initialized
2022-04-12 09:12:36,767 ERROR :: Connection Error while making GET request to /api/v1/instrument/active: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/instrument/active (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ABB1F5AD70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:12:36,767 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:36,770 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:36,771 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:48,804 ERROR :: Connection Error while making GET request to /api/v1/user/margin: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/user/margin?currency=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001ABB1F5A530>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:12:48,805 INFO :: Bitmex Client Successfully Initialized
2022-04-12 09:12:49,289 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:49,291 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:49,292 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:50,803 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:50,803 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:50,804 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:51,294 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:51,295 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:51,295 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:52,806 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:52,807 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:52,807 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:53,307 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:53,308 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:53,308 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:54,815 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:54,815 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:54,816 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:55,316 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:55,316 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:55,316 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:56,818 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:56,818 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:56,818 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:57,326 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:57,327 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:57,327 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:58,826 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:58,826 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:58,826 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:59,341 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:12:59,341 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:12:59,341 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:13:00,840 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:13:00,841 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001ABB1F590F0>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:13:00,841 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:13:08,743 ERROR :: Bitmex connection error: [WinError 10054] An existing connection was forcibly closed by the remote host
2022-04-12 09:13:08,748 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001ABB1F598A0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:13:08,748 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:13:10,041 INFO :: Binance connection opened
2022-04-12 09:13:12,232 INFO :: Bitmex connection opened
2022-04-12 09:16:12,118 INFO :: Binance Futures Client successfully Initialized
2022-04-12 09:16:13,069 INFO :: Binance connection opened
2022-04-12 09:16:13,387 INFO :: Bitmex Client Successfully Initialized
2022-04-12 09:16:15,221 INFO :: Bitmex connection opened
2022-04-12 09:18:38,553 INFO :: Binance Futures Client successfully Initialized
2022-04-12 09:18:39,479 INFO :: Binance connection opened
2022-04-12 09:18:39,708 INFO :: Bitmex Client Successfully Initialized
2022-04-12 09:18:41,424 INFO :: Bitmex connection opened
2022-04-12 09:20:28,420 ERROR :: Error while making GET request to /fapi/v1/account:{'code': -1021, 'msg': 'Timestamp for this request is outside of the recvWindow.'} (Error Code:400)
2022-04-12 09:20:28,420 INFO :: Binance Futures Client successfully Initialized
2022-04-12 09:20:40,883 INFO :: Binance connection opened
2022-04-12 09:21:16,011 ERROR :: Binance connection error: Connection to remote host was lost.
2022-04-12 09:21:16,011 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000001BD97B8BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:16,011 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:19,131 INFO :: Bitmex Client Successfully Initialized
2022-04-12 09:21:30,298 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:30,298 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000001BD97B98A60>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:30,299 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:51,294 ERROR :: Connection Error while making GET request to /fapi/v1/exchangeInfo: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/exchangeInfo (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002174214B880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:21:51,299 ERROR :: Connection Error while making GET request to /fapi/v1/account: HTTPSConnectionPool(host='testnet.binancefuture.com', port=443): Max retries exceeded with url: /fapi/v1/account?timestamp=1649735511294&signature=fba9770a33a431e8e339686b6a0c486791f35eb3954db5d680871c0747bd7045 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002174214AF50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:21:51,301 INFO :: Binance Futures Client successfully Initialized
2022-04-12 09:21:51,301 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:51,303 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002174214BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:51,303 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:51,309 ERROR :: Connection Error while making GET request to /api/v1/instrument/active: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/instrument/active (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002174214AB90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:21:51,314 ERROR :: Connection Error while making GET request to /api/v1/user/margin: HTTPSConnectionPool(host='testnet.bitmex.com', port=443): Max retries exceeded with url: /api/v1/user/margin?currency=all (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002174214AD70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2022-04-12 09:21:51,315 INFO :: Bitmex Client Successfully Initialized
2022-04-12 09:21:51,315 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:51,724 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000002174214A3B0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:51,724 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:53,310 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:53,311 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002174214BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:53,311 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:53,739 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:53,739 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000002174214A3B0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:53,739 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:55,326 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:55,327 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002174214BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:55,327 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:55,753 ERROR :: Bitmex connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:55,754 ERROR :: error from callback <bound method BitmexClient._on_close of <connectors.bitmex.BitmexClient object at 0x000002174214A3B0>>: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:55,754 ERROR :: Bitmex connection error: BitmexClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:57,343 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:21:57,345 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002174214BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:21:57,345 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:22:04,473 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:22:04,473 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002174214BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:22:04,474 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:22:06,478 ERROR :: Binance connection error: [Errno 11001] getaddrinfo failed
2022-04-12 09:22:06,478 ERROR :: error from callback <bound method BinanceFuturesClient._on_close of <connectors.binance_futures.BinanceFuturesClient object at 0x000002174214BD30>>: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:22:06,478 ERROR :: Binance connection error: BinanceFuturesClient._on_close() takes 2 positional arguments but 4 were given
2022-04-12 09:22:09,419 INFO :: Binance connection opened
2022-04-12 09:22:10,736 INFO :: Bitmex connection opened
2022-04-15 22:08:41,999 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:08:42,651 INFO :: Binance connection opened
2022-04-15 22:08:42,954 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:08:44,830 INFO :: Bitmex connection opened
2022-04-15 22:08:47,473 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:08:47,490 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:08:51,582 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:08:56,028 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:02,027 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:06,542 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:11,032 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:17,041 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:21,531 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:26,030 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:32,032 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:09:36,533 INFO :: XBTUSD 40292 / 40302.5
2022-04-15 22:52:57,480 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:52:58,050 INFO :: Binance connection opened
2022-04-15 22:52:58,253 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:52:59,088 INFO :: Bitmex connection opened
2022-04-15 22:53:30,770 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:53:31,259 INFO :: Binance connection opened
2022-04-15 22:53:31,840 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:53:33,157 INFO :: Bitmex connection opened
2022-04-15 22:57:52,420 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:57:53,002 INFO :: Binance connection opened
2022-04-15 22:57:53,442 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:57:54,282 INFO :: Bitmex connection opened
2022-04-15 22:58:33,641 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:58:34,115 INFO :: Binance connection opened
2022-04-15 22:58:34,272 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:58:35,234 INFO :: Bitmex connection opened
2022-04-15 22:58:56,498 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:58:57,102 INFO :: Binance connection opened
2022-04-15 22:58:57,293 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:58:58,677 INFO :: Bitmex connection opened
2022-04-15 22:59:19,142 INFO :: Binance Futures Client successfully Initialized
2022-04-15 22:59:19,687 INFO :: Binance connection opened
2022-04-15 22:59:19,785 INFO :: Bitmex Client Successfully Initialized
2022-04-15 22:59:20,586 INFO :: Bitmex connection opened
2022-04-15 23:01:58,885 INFO :: Binance Futures Client successfully Initialized
2022-04-15 23:01:59,483 INFO :: Binance connection opened
2022-04-15 23:02:00,009 INFO :: Bitmex Client Successfully Initialized
2022-04-15 23:02:00,734 INFO :: Bitmex connection opened
2022-04-15 23:03:02,339 INFO :: Binance Futures Client successfully Initialized
2022-04-15 23:03:02,917 INFO :: Binance connection opened
2022-04-15 23:03:03,801 INFO :: Bitmex Client Successfully Initialized
2022-04-15 23:03:05,179 INFO :: Bitmex connection opened
2022-04-15 23:13:40,823 INFO :: Binance Futures Client successfully Initialized
2022-04-15 23:13:41,382 INFO :: Binance connection opened
2022-04-15 23:13:41,804 INFO :: Bitmex Client Successfully Initialized
2022-04-15 23:13:43,146 INFO :: Bitmex connection opened
2022-04-15 23:14:59,954 INFO :: Binance Futures Client successfully Initialized
2022-04-15 23:15:00,498 INFO :: Binance connection opened
2022-04-15 23:15:01,068 INFO :: Bitmex Client Successfully Initialized
2022-04-15 23:15:02,383 INFO :: Bitmex connection opened
2022-04-15 23:15:34,995 INFO :: Binance Futures Client successfully Initialized
2022-04-15 23:15:35,464 INFO :: Binance connection opened
2022-04-15 23:15:36,192 INFO :: Bitmex Client Successfully Initialized
2022-04-15 23:15:36,960 INFO :: Bitmex connection opened
